discovery.params.prod.x1=prodX1
discovery.params.prod.x2=prodX2


spring.datasource.url=jdbc:h2:mem:product-prod-db
spring.h2.console.enabled=true


#search for config server/service
spring.cloud.config.enabled=false

spring.data.rest.base-path=/api

#pour afficher tout les options de actuator /beans /caches, .../refresh
management.endpoints.web.exposure.include=*


#search discovery service
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
