spring.application.name=config-service
server.port=9999
spring.cloud.config.server.git.uri=file:///C:/Users/Windows/Documents/entretiens/Eecom-micro-service-app/config-repo/
spring.cloud.config.server.git.search-paths=customer-service, billing-service, invintory-service